FROM archlinux:base

RUN pacman -Syu --noconfirm \
        bash \
        git \
        openssh \
        tmux \
    && pacman -Scc --noconfirm

RUN useradd -m -s /bin/bash testuser

COPY git-harden.sh /home/testuser/git-harden.sh
COPY test/ /home/testuser/test/
RUN chown -R testuser:testuser /home/testuser

USER testuser
WORKDIR /home/testuser

RUN git config --global user.name "Test User" \
    && git config --global user.email "test@example.com"

CMD ["bash", "test/run.sh"]
